import "./globals.css";

export const metadata = {
  title: "Givefy",
  description: "Generated by Giveth Developer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" />
      </head>
      <body
        className={`bg-blue-950 text-black flex flex-col items-center justify-center h-[100dvh] overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
